<table id="<?=$this->getId()?>" class="table table-striped" cellspacing="0" width="100%">
    <thead>
    <tr>
        <?php foreach ($this->getColumns() as $column): ?>
            <th <?php foreach ($column->getAttributes() as $attribute => $value): ?><?=$attribute?>="<?=$value?>"<?php endforeach ?>>
                <?php if (!$column->getOption('hideName')): ?>
                    <?=$column->getName()?>
                <?php endif ?>
            </th>
        <?php endforeach ?>
    </tr>
    </thead>

    <tfoot>
    <tr>
        <?php foreach ($this->getColumns() as $column): ?>
            <th>
                <?php if (!$column->getOption('hideName')): ?>
                    <?=$column->getName()?>
                <?php endif ?>
            </th>
        <?php endforeach ?>
    </tr>
    </tfoot>
</table>

<script>
    var table = $('#<?=$this->getId()?>').dataTable({
        stateSave: true,
        columns: [
            <?php foreach ($this->getColumns() as $key => $column): ?>
                <?=$key != 0 ? ',' : ''?>{data: "<?=$column->getName()?>", orderable: <?=$column->getOption('orderable') === true ? 'true' : 'false'?>}
            <?php endforeach ?>
        ],
        ajax: {
            url: "",
            data: function (d) {
                d.datagrid = '<?=$this->getId()?>'
            }
        },
        processing: true,
        serverSide: true,
        language: {
            "sProcessing": "Bezig...",
            "sLengthMenu": "_MENU_ resultaten weergeven",
            "sZeroRecords": "Geen data om weer te geven",
            "sInfo": "Resulaten _START_ tot _END_ van _TOTAL_ weergegeven",
            "sInfoEmpty": "Geen data om weer te geven",
            "sInfoFiltered": " (gefilterd uit _MAX_ regels)",
            "sInfoPostFix": "",
            "sSearch": "Zoeken:",
            "sEmptyTable": "Geen gegevens aanwezig in de tabel",
            "sInfoThousands": ",",
            "sLoadingRecords": "Een moment geduld aub - bezig met laden...",
            "oPaginate": {
                "sFirst": "Eerste pagina",
                "sLast": "Laatste pagina",
                "sNext": "Volgende pagina",
                "sPrevious": "Vorige pagina"
            }
        }
    });
</script>